//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "bot_statistics")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub bot_id: Uuid,
    pub total_games: i32,
    pub wins: i32,
    pub second_place: i32,
    pub third_place: i32,
    pub fourth_place: i32,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub average_score: Option<Decimal>,
    pub peak_mmr: Option<i32>,
    pub current_streak: i32,
    pub last_game_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub uptime_percentage: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bot::Entity",
        from = "Column::BotId",
        to = "super::bot::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Bot,
}

impl Related<super::bot::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bot.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
