//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub mod prelude;

pub mod bot;
pub mod game_history;
pub mod lobby_pool;
pub mod r#match;
pub mod private_room;
pub mod queue;
pub mod report;
pub mod room_invitation;
pub mod room_participants;
pub mod user;
pub mod user_session;

pub use bot::Entity as Bot;
pub use game_history::Entity as GameHistory;
pub use lobby_pool::Entity as LobbyPool;
pub use r#match::Entity as Match;
pub use private_room::Entity as PrivateRoom;
pub use queue::Entity as Queue;
pub use report::Entity as Report;
pub use room_invitation::Entity as RoomInvitation;
pub use room_participants::Entity as RoomParticipants;
pub use user::Entity as User;
pub use user_session::Entity as UserSession;
