//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "match")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub lobby_id: Uuid,
    pub game_history_id: Uuid,
    pub started_at: DateTimeWithTimeZone,
    pub completed_at: Option<DateTimeWithTimeZone>,
    pub participant1_type: String,
    pub participant1_id: Uuid,
    pub participant1_score: Option<i32>,
    pub participant1_mmr_delta: Option<i32>,
    pub participant2_type: String,
    pub participant2_id: Uuid,
    pub participant2_score: Option<i32>,
    pub participant2_mmr_delta: Option<i32>,
    pub participant3_type: String,
    pub participant3_id: Uuid,
    pub participant3_score: Option<i32>,
    pub participant3_mmr_delta: Option<i32>,
    pub participant4_type: Option<String>,
    pub participant4_id: Option<Uuid>,
    pub participant4_score: Option<i32>,
    pub participant4_mmr_delta: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::game_history::Entity",
        from = "Column::GameHistoryId",
        to = "super::game_history::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    GameHistory,
    #[sea_orm(
        belongs_to = "super::lobby_pool::Entity",
        from = "Column::LobbyId",
        to = "super::lobby_pool::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    LobbyPool,
    #[sea_orm(has_many = "super::report::Entity")]
    Report,
}

impl Related<super::game_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GameHistory.def()
    }
}

impl Related<super::lobby_pool::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LobbyPool.def()
    }
}

impl Related<super::report::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Report.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
