//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "private_room")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub host_id: Uuid,
    pub room_name: String,
    #[sea_orm(unique)]
    pub room_code: String,
    pub password: Option<String>,
    pub max_players: i32,
    pub allow_bots: bool,
    pub invite_only: bool,
    pub status: String,
    pub room_settings: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub completed_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::room_invitation::Entity")]
    RoomInvitation,
    #[sea_orm(has_many = "super::room_participants::Entity")]
    RoomParticipants,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::HostId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::room_invitation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RoomInvitation.def()
    }
}

impl Related<super::room_participants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RoomParticipants.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
