//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "queue")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub participant_type: String,
    pub participant_id: Uuid,
    pub lobby_id: Uuid,
    pub preferred_mmr_range: Option<String>,
    pub joined_at: DateTimeWithTimeZone,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::lobby_pool::Entity",
        from = "Column::LobbyId",
        to = "super::lobby_pool::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    LobbyPool,
}

impl Related<super::lobby_pool::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LobbyPool.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
