//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "room_participants")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub room_id: Uuid,
    pub participant_type: String,
    pub participant_id: Uuid,
    pub status: String,
    pub joined_at: DateTimeWithTimeZone,
    pub left_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::private_room::Entity",
        from = "Column::RoomId",
        to = "super::private_room::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PrivateRoom,
}

impl Related<super::private_room::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PrivateRoom.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
