//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub username: String,
    pub country: String,
    pub favorite_tile: Option<String>,
    pub pronouns: Option<String>,
    pub matchmaking_rank: i32,
    pub password: String,
    pub created_at: DateTimeWithTimeZone,
    pub passkey: Option<Json>,
    pub role: String,
    pub email: Option<String>,
    pub last_active_at: Option<DateTimeWithTimeZone>,
    pub account_status: String,
    pub settings: Option<Json>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::bot::Entity")]
    Bot,
    #[sea_orm(has_many = "super::user_session::Entity")]
    UserSession,
}

impl Related<super::bot::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bot.def()
    }
}

impl Related<super::user_session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSession.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
